//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastOasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouriteFilm
    {
        public string userId { get; set; }
        public string filmId { get; set; }
        public string film_name { get; set; }
        public string favouriteFilmId { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
