//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastOasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string userId { get; set; }
        public string filmId { get; set; }
        public string filmName { get; set; }
        public string rate { get; set; }
        public string comment { get; set; }
        public System.DateTime date { get; set; }
        public string ratingId { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
